### ISSUE TITLE
Crash with or without OptiFine

### ISSUE THREAD

**Issue by Fogrits** [GenDeathrow/Hatchery#48]
[08:24:33] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
	at net.minecraft.world.biome.Biome.func_76747_a(Biome.java:173) ~[aiq.class:?]
	at net.minecraft.world.gen.ChunkProviderFlat.func_177458_a(ChunkProviderFlat.java:230) ~[aty.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_177458_a(ChunkProviderServer.java:298) ~[lr.class:?]
	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:239) ~[ls.class:?]
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:126) ~[aik.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198) ~[ls.class:?]
	at WorldServerOF.func_72835_b(WorldServerOF.java:37) ~[WorldServerOF.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) ~[MinecraftServer.class:?]
	... 4 more

The world loads upon removing the mod.
Update: OptiFine's presence doesn't change anything, only remove one line from the crash report.
PS: Latest version = v0.2.7 (Fix update)

**Comment by Fogrits** [comment]
Curiously this crash also happens with Quark installed, Idk why.

**Comment by Fogrits** [comment]
Solved by removing Mo' Villages from mods folder.
