### ISSUE TITLE
NPE WAILA Spam/Crash (SF3)

### ISSUE THREAD

**Issue by FiveEYZ** [GenDeathrow/Hatchery#53]
https://hastebin.com/edotojasij.vbs

this error gets spammed in latest.log as long as u are looking at a "Hatchery Nest"
SkyFactory 3 3.0.6 server

after a while this error happens:
https://hastebin.com/inorucozel.rb

- everyone will get disconnected from the server
- when trying to connect again they will just see "timed out"
- same time this shows in the log: https://hastebin.com/wudohafuti.rb

**Comment by GenDeathrow** [comment]
Strange first time I have seen this issue ever. Ill look into catching the null pointer. Try and get an update out later in the day.

**Comment by GenDeathrow** [comment]
I looked into this, this may not be an issue with hatchery technically, but an issue with the mod that has taken over waila. I give you more information when I get it.

**Comment by andremiller** [comment]
We're playing SkyFactory 3.0.6, and up until today didn't have any problems with chickens. When a player looks at a nest (which worked before), it's giving all the null pointer exceptions in the server log and kicking all the players from the server.

After doing a bit of research it seemed that updating Hwyla might fix it. We updated to Hwyla-1.8.10-B24 on the server and all clients, but it's still doing the same.

Example of log after the Hwyla update:

```
[21:14:34] [Server thread/FATAL]: Error executing task                                                                                                      │·························
java.util.concurrent.ExecutionException: java.lang.NullPointerException                                                                                     │·························        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]                                                                       │·························
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]                                                                          │·························
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]                                                                                 │·························
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]                                            │·························
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]                                               │·························
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]                                            │·························
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]                                                     │·························
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]                                                                                              │·························
Caused by: java.lang.NullPointerException                                                                                                                   │·························
        at com.gendeathrow.hatchery.core.waila.HatcheryTileProvider.getNBTData(HatcheryTileProvider.java:145) ~[HatcheryTileProvider.class:?]               │·························
        at mcp.mobius.waila.network.MessageRequestTile$Handler$1.run(MessageRequestTile.java:100) ~[MessageRequestTile$Handler$1.class:?]                   │·························
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]                                                           │·························
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]                                                                          │·························
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]                                                                                │·························
        ... 5 more                
```

**Comment by GenDeathrow** [comment]
Try updating hatchery to the latest as well tell me it if works.

**Comment by andremiller** [comment]
Thanks @GenDeathrow GenDeathrow, that worked. Updated to hatchery-1.10.2-0.2.10.jar and the log was clean, no client crashes.

Of course, just after doing these updates manually, SkyFactory 3.0.7 was released, which already includes them!
