### ISSUE TITLE
excessive Null pointer spam when Waila isn't installed

### ISSUE THREAD

**Issue by antisocialian** [GenDeathrow/Hatchery#55]
I'm playing on SkyFactory 3 and for some reason it doesn't have Waila installed, but instead chose the fork of it Hwyla.

When I look at a nest, i get an extreme amount of spam in the console(enough to lag the server). The error seems to be: 
`[13:09:46] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.gendeathrow.hatchery.core.waila.HatcheryTileProvider.getNBTData(HatcheryTileProvider.java:145) ~[HatcheryTileProvider.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler$1.run(MessageRequestTile.java:100) ~[MessageRequestTile$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more`

I've attached the latest.log file from my session where i first made the nest. The errors start at line 75, for reference, Line 24222 thru 29083 are just the errors from me looking at it enough to put an egg in the nest.
[latest.log.txt](https://github.com/GenDeathrow/Hatchery/files/745735/latest.log.txt)

**Comment by antisocialian** [comment]
If i disable Hwyla using the in game options(default key: NumPad 0) then the spam doesn't show up.

**Comment by GenDeathrow** [comment]
This is a known issue. something changed in the last version of HWYLA, which is a a continueation of wailia. Up until now its worked fine. it says wailia because Hwyla is bavkward compatable or was. Ill be looking into the issue soon.

**Comment by antisocialian** [comment]
it is also seems to be only empty nests, once the egg is in the nest it doesn't have the error.

maybe Empty Nest Syndrome? :D

**Comment by GenDeathrow** [comment]
well Im catching a null issue with the egg now. Im hoping that fixes that one. now to figure out the others

**Comment by GenDeathrow** [comment]
Moving this over here.. https://github.com/GenDeathrow/Hatchery/issues/53
