### ISSUE TITLE
Sky Factory 3 Crash

### ISSUE THREAD

**Issue by AGWeeB** [GenDeathrow/Hatchery#62]
I am playing Sky factory 3 currently and experiencing a crash with the below error. When this occur my game freezes and I have to kill it. When looking at the logs I see this error over and over until I killed the game.

http://pastebin.com/UxqpT4Rg

[09:47:30] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at com.gendeathrow.hatchery.core.waila.HatcheryTileProvider.getNBTData(HatcheryTileProvider.java:145) ~[HatcheryTileProvider.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler$1.run(MessageRequestTile.java:100) ~[MessageRequestTile$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/issues/53

**Comment by AGWeeB** [comment]
Thank you I will try updating to Hwyla-1.8.10-B24 and let you know if I see it again.

**Comment by GenDeathrow** [comment]
Ok my keyboard wasn't working on my phone. It is now. HEy MA changed something all you have to do Is update to the latest.

**Comment by AGWeeB** [comment]
Thanks...I am assuming you meant HWYLA? haha

**Comment by GenDeathrow** [comment]
If your on a server I'm not sure if the whole server needs an update or not.

**Comment by AGWeeB** [comment]
So I think there is still an issue here. I upgraded to Hwyla-1.8.10-B24 and while the issue does not occur in an infinite loop and crash my game. the error does still come up when looking at an empty nest. Other than that is doesn't seem to occur. So while the error don't seem to be crashing my game I definitely still see the errors in the console.

**Comment by GenDeathrow** [comment]
I believe I have an update that may fix that.. getting time to publish it has been rough. It still was because HWYLA changed how they handle stuff as this wants an issue before.  But I have a null check now. Hopfully i can get an update out tonight.

**Comment by AGWeeB** [comment]
Awesome. Dont worry about it, I know how hard time can be to come by. At the moment with the upgrade of HWYLA it at least isn't game breaking issue as long as you don't stare at an empty nest. haha

Thanks so much for the prompt response and hard work on the mod. I am always amazed at the response and activity of the developers in this modded minecraft community.
